// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOR6fjYvH0x6dTZPBAcfoQZZXy47JZhfs',
    appId: '1:364242849589:web:c999d48440d7dae0a0c67c',
    messagingSenderId: '364242849589',
    projectId: 'appflutter-491a9',
    authDomain: 'appflutter-491a9.firebaseapp.com',
    storageBucket: 'appflutter-491a9.firebasestorage.app',
    measurementId: 'G-YZFX1R8YSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxV79ndnrFf-62pe_gqvY5s4bBHAft7RE',
    appId: '1:364242849589:android:a0b7e47724f57290a0c67c',
    messagingSenderId: '364242849589',
    projectId: 'appflutter-491a9',
    storageBucket: 'appflutter-491a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsaFtBafqFQYWWwUYL9lQ3Pl4s1MkmC8k',
    appId: '1:364242849589:ios:4a0a6ddb58e1b68ea0c67c',
    messagingSenderId: '364242849589',
    projectId: 'appflutter-491a9',
    storageBucket: 'appflutter-491a9.firebasestorage.app',
    iosBundleId: 'com.example.appdenotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsaFtBafqFQYWWwUYL9lQ3Pl4s1MkmC8k',
    appId: '1:364242849589:ios:4a0a6ddb58e1b68ea0c67c',
    messagingSenderId: '364242849589',
    projectId: 'appflutter-491a9',
    storageBucket: 'appflutter-491a9.firebasestorage.app',
    iosBundleId: 'com.example.appdenotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOR6fjYvH0x6dTZPBAcfoQZZXy47JZhfs',
    appId: '1:364242849589:web:1852946b4b164413a0c67c',
    messagingSenderId: '364242849589',
    projectId: 'appflutter-491a9',
    authDomain: 'appflutter-491a9.firebaseapp.com',
    storageBucket: 'appflutter-491a9.firebasestorage.app',
    measurementId: 'G-EWKQ74W7Z6',
  );
}
